In [1]:
import openpyxl

def read_data
wb = openpyxl.load_workbook("bm/Data/model1_data1.xlsx", read_only=True)
print(wb.sheetnames)
ws = wb["Exp Data"]

# some applications set the worksheet information incorrectly
# so, reset dimension attributes
ws.max_row = ws.max_column = None

for row in ws.rows:
    for cell in row:
        print(cell.value)

['Exp Data', 'Simulation']
time
pEGFR_tot
pEGFR_tot_std
pEGFR_tot_ExpError
pAkt_tot
pAkt_tot_std
pAkt_tot_ExpError
pS6_tot
pS6_tot_std
pS6_tot_ExpError
0.0
0.0

0.01
0.0

0.01
0.0

0.01
60.0
0.004955

0.01
0.031232

0.01
0.0018563

0.01
120.0
0.004034

0.01
0.093444

0.01
0.0033416

0.01
300.0
0.0063674

0.01
0.23689

0.01
0.012632

0.01
600.0
0.010859

0.01
0.14973

0.01
0.078914

0.02
900.0
0.0071353

0.01
0.093097

0.01
0.25521

0.02
1800.0
0.0037103

0.01
0.065764

0.01
0.44745

0.035
3600.0
0.0067693

0.01
0.045765

0.01
0.29547

0.035

In [14]:
import pandas as pd
df = pd.read_excel("bm/Data/model1_data1.xlsx", sheet_name=0, header=0)
df

,time,pEGFR_tot,pEGFR_tot_std,pEGFR_tot_ExpError,pAkt_tot,pAkt_tot_std,pAkt_tot_ExpError,pS6_tot,pS6_tot_std,pS6_tot_ExpError
0,0,0.000000,NaN,0.01,0.000000,NaN,0.01,0.000000,NaN,0.010
1,60,0.004955,NaN,0.01,0.031232,NaN,0.01,0.001856,NaN,0.010
2,120,0.004034,NaN,0.01,0.093444,NaN,0.01,0.003342,NaN,0.010
3,300,0.006367,NaN,0.01,0.236890,NaN,0.01,0.012632,NaN,0.010
4,600,0.010859,NaN,0.01,0.149730,NaN,0.01,0.078914,NaN,0.020
5,900,0.007135,NaN,0.01,0.093097,NaN,0.01,0.255210,NaN,0.020
6,1800,0.003710,NaN,0.01,0.065764,NaN,0.01,0.447450,NaN,0.035
7,3600,0.006769,NaN,0.01,0.045765,NaN,0.01,0.295470,NaN,0.035